import"./assets/styles-a-Q9RkeZ.js";import{a as d,i as _}from"./assets/vendor-Cbhu4xvy.js";const r={form:document.querySelector(".search-form"),categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),loadMore:document.querySelector(".load-more-btn"),card:document.querySelector(".products__item")};async function h(){try{return await d.get("https://dummyjson.com/products/category-list")}catch(t){console.log(t.message)}}const u=12;async function p(t){const e={limit:u,skip:(t-1)*12,orientation:"portrait"};try{return await d.get("https://dummyjson.com/products/",{params:e})}catch(o){console.log(o.message)}}async function m(t,e){const o={limit:12,skip:(e-1)*12,orientation:"portrait"};try{return await d.get(`https://dummyjson.com/products/category/${t}`,{params:o})}catch(s){console.log(s.message)}}function L(t){return t.unshift("All"),t.map(e=>`
    <li class="categories__item">
      <button class="categories__btn" type="button">${e}</button>
    </li>`).join("")}function n(t){return t.map(e=>`
    <li class="products__item" data-id="${e.id}">
      <img class="products__image" src="${e.thumbnail}" alt="${e.description}"/>
      <p class="products__title">${e.title}</p>
      <p class="products__brand"><span class="products__brand--bold">Brand: ${e.brand}</span></p>
      <p class="products__category">Category: ${e.category}  </p>
      <p class="products__price">Price: ${e.price}$</p>
    </li>`).join("")}function g(){r.loadMore.classList.add("hidden")}function i(){r.loadMore.classList.remove("hidden")}let a=1,l,c;async function f(){a=1,g();try{const t=await h();r.categoriesList.innerHTML=L(t.data),document.querySelector(".categories__btn").closest(".categories__btn").classList.add("categories__btn--active"),c="All";const o=await p(a);if(o.data.products===0)throw _.error({title:"Error",message:"Sorry, there are no images. Please try again!"}),new Error("Sorry, there are no images. Please try again!");r.productsList.innerHTML=n(o.data.products),l=Math.ceil(o.data.total/u),console.log(l),i()}catch(t){console.log(t.message)}}async function b(t){if(g(),a=1,document.querySelectorAll(".categories__btn").forEach(s=>s.classList.remove("categories__btn--active")),t.target.nodeName!=="BUTTON")return;c=t.target.textContent,t.target.closest(".categories__btn").classList.add("categories__btn--active");try{const s=await m(c,a);if(r.productsList.innerHTML=n(s.data.products),l=Math.ceil(s.data.total/u),console.log(l),c==="All"){const y=await p(a);r.productsList.innerHTML=n(y.data.products)}i()}catch(s){console.log(s.message)}}async function M(){a+=1,g();try{const e=document.querySelector(".products__item").getBoundingClientRect().height;if(c==="All"){const s=await p(a);r.productsList.insertAdjacentHTML("beforeend",n(s.data.products)),window.scrollBy({top:e,behavior:"smooth"}),i()}const o=await m(c,a);r.productsList.insertAdjacentHTML("beforeend",n(o.data.products)),window.scrollBy({top:e,behavior:"smooth"}),i()}catch(t){console.log(t.message)}}document.addEventListener("DOMContentLoaded",f);r.categoriesList.addEventListener("click",b);r.loadMore.addEventListener("click",M);
//# sourceMappingURL=index.js.map
